name: apache-bigdata-siem

x-common-env: &common-env
  networks: [siem-network]
  restart: unless-stopped

x-spark-common: &spark-common
  <<: *common-env
  build: ./config/spark
  volumes:
    - ./config/spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf:ro
    - ./config/hadoop/core-site.xml:/opt/bitnami/spark/conf/core-site.xml:ro
    - ./config/hadoop/hdfs-site.xml:/opt/bitnami/spark/conf/hdfs-site.xml:ro
    - ./config/hive/hive-site.xml:/opt/bitnami/spark/conf/hive-site.xml:ro
    - ./config/spark/jobs:/opt/bitnami/spark/jobs

services:
  # ─────────────────────────────────────────────────────────
  # STORAGE LAYER
  # ─────────────────────────────────────────────────────────
  namenode:
    <<: *common-env
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment: { CLUSTER_NAME: siem-hdfs, CORE_CONF_fs_defaultFS: "hdfs://namenode:8020" }
    ports: ["9870:9870", "8020:8020"]
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./config/hadoop/core-site.xml:/etc/hadoop/core-site.xml:ro
      - ./config/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870/dfshealth.html || exit 1"]

  datanode:
    <<: *common-env
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment: { CORE_CONF_fs_defaultFS: "hdfs://namenode:8020" }
    depends_on: { namenode: { condition: service_healthy } }
    volumes:
      - datanode-1-data:/hadoop/dfs/data
      - ./config/hadoop/core-site.xml:/etc/hadoop/core-site.xml:ro
      - ./config/hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:ro

  postgres:
    <<: *common-env
    image: postgres:15-alpine
    container_name: siem-postgres
    environment: { POSTGRES_DB: metastore, POSTGRES_USER: hive, POSTGRES_PASSWORD: hivepass }
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/postgres/init-superset-db.sh:/docker-entrypoint-initdb.d/init-superset-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]

  hive-metastore:
    <<: *common-env
    image: apache/hive:4.0.0
    container_name: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=hivepass"
    depends_on: { postgres: { condition: service_healthy }, namenode: { condition: service_healthy } }
    volumes:
      - hive-warehouse:/opt/hive/data/warehouse
      - ./config/hive/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./config/hadoop/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml:ro
      - ./config/hive/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/9083'"]

  # ─────────────────────────────────────────────────────────
  # DATA ENGINE
  # ─────────────────────────────────────────────────────────
  kafka-broker:
    <<: *common-env
    image: bitnamilegacy/kafka:3.7.1-debian-12-r9
    container_name: kafka-broker
    environment:
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_KRAFT_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports: ["9092:9092"]
    volumes: [ "kafka-data:/bitnami/kafka" ]
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]

  spark-master:
    <<: *spark-common
    container_name: spark-master
    environment: { SPARK_MODE: master, SPARK_RPC_AUTHENTICATION_ENABLED: "no" }
    command: /opt/bitnami/scripts/spark/run.sh
    ports: ["8080:8080"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]

  spark-worker:
    <<: *spark-common
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
    deploy: { replicas: 2 }
    depends_on: { spark-master: { condition: service_healthy } }

  spark-thrift:
    <<: *spark-common
    container_name: spark-thrift
    environment: { SPARK_MODE: client }
    command: >
      /opt/bitnami/spark/bin/spark-submit
      --master spark://spark-master:7077
      --conf spark.server2.thrift.port=10000
      --conf spark.server2.thrift.bind.host=0.0.0.0
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      spark-internal
    ports: ["10000:10000"]
    depends_on: { spark-master: { condition: service_healthy } }

  siem-engine:
    <<: *spark-common
    container_name: siem-engine
    depends_on: { spark-thrift: { condition: service_started }, kafka-broker: { condition: service_healthy } }
    command: >
      /bin/bash -c "
        echo 'Waiting for Spark Cluster...' &&
        sleep 20 &&
        spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6 /opt/bitnami/spark/jobs/etl_process.py &
        spark-submit --master spark://spark-master:7077 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.6 /opt/bitnami/spark/jobs/streaming_kmeans.py &
        wait
      "

  # ─────────────────────────────────────────────────────────
  # SIEM APPLICATIONS
  # ─────────────────────────────────────────────────────────
  kafka-producer:
    <<: *common-env
    build: ./config/kafka
    container_name: kafka-producer
    environment: { KAFKA_BOOTSTRAP_SERVERS: 'kafka-broker:9092', DATA_FILE: '/data/conn.log' }
    volumes: [ "./data:/data:ro" ]
    depends_on: { kafka-broker: { condition: service_healthy } }

  superset:
    <<: *common-env
    image: apache/superset:4.1.1
    container_name: superset
    user: root
    environment:
      SUPERSET_SECRET_KEY: f8d93a10-2b4a-4e2b-b893-ecf9e2b1029c
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://superset:superset123@siem-postgres:5432/superset
      PYTHONPATH: /app/pythonpath:/app/config
      SUPERSET_CONFIG_PATH: /app/config/superset_config.py
    ports: ["8088:8088"]
    volumes:
      - superset_data:/app/superset_home
      - ./config/superset/superset_init.sh:/app/superset_init.sh:ro
      - ./config/superset/superset_config.py:/app/config/superset_config.py:ro
      - ./config/tools:/app/scripts:ro
    command: bash /app/superset_init.sh
    depends_on: { postgres: { condition: service_healthy } }

  zeppelin:
    <<: *common-env
    build: ./config/zeppelin
    container_name: zeppelin
    environment: { SPARK_MASTER: 'spark://spark-master:7077', ZEPPELIN_ADDR: '0.0.0.0' }
    ports: ["9090:8080"]
    volumes:
      - zeppelin-data:/opt/zeppelin/notebook
      - zeppelin-logs:/opt/zeppelin/logs
      - ./config/zeppelin:/opt/zeppelin/notebook_import:ro
      - ./config/hadoop/core-site.xml:/opt/zeppelin/conf/hadoop/core-site.xml:ro
      - ./config/hadoop/hdfs-site.xml:/opt/zeppelin/conf/hadoop/hdfs-site.xml:ro
      - ./config/hive/hive-site.xml:/opt/zeppelin/conf/hadoop/hive-site.xml:ro
      - ./data:/opt/zeppelin/data:ro
      - ./config/spark/jobs:/opt/zeppelin/jobs:ro
    depends_on: { spark-master: { condition: service_healthy }, kafka-broker: { condition: service_healthy } }

networks:
  siem-network: { name: siem-network }

volumes:
  namenode-data:
  datanode-1-data:
  postgres-data:
  kafka-data:
  hive-warehouse:
  superset_data:
  zeppelin-data:
  zeppelin-logs:
