# **Büyük Veri SIEM Ortamlarında Apache Zeppelin Çekirdek Mimarisi ve İnteraktif Tehdit Avcılığı Analizi**

Geleneksel Güvenlik Bilgi ve Olay Yönetimi (SIEM) mimarileri, artan veri hacimleri, karmaşıklaşan siber saldırı vektörleri ve gelişmiş kalıcı tehditlerin (APT) yatay hareketlerini tespit etme konusundaki yetersizlikleri nedeniyle evrimleşmek zorunda kalmıştır. Salt ilişkisel veritabanlarına veya statik indeksleme motorlarına dayalı sistemler, petabaytlarca ağ trafiği, uç nokta tespiti (EDR) logu ve kimlik doğrulama verisiyle karşılaştıklarında ciddi performans darboğazları yaratmaktadır.1 Bu kısıtlamaları aşmak amacıyla modern Siber Güvenlik Operasyon Merkezleri (SOC), Apache Spark, Hadoop Dağıtık Dosya Sistemi (HDFS) ve Apache Kafka gibi teknolojiler üzerine inşa edilen "Veri Gölü" (Data Lakehouse) tabanlı büyük veri SIEM boru hatlarına (pipeline) yönelmiştir.2  
Bu yeni nesil ekosistemin merkezinde, veriyi işleyen motorlar ile bu veriyi sorgulayan güvenlik analistleri arasında interaktif bir köprü görevi gören Apache Zeppelin yer almaktadır. Web tabanlı, çok dilli ve paylaşımlı bir analitik not defteri (notebook) olan Apache Zeppelin (v0.11.1), veri keşfi, veri temizleme (data cleansing), anomali tespiti ve görselleştirme süreçlerinin tek bir entegre ortamda yürütülmesine olanak tanır.4 Standart bir raporlama aracından farklı olarak Zeppelin, "İnteraktif Tehdit Avcılığı" (Interactive Threat Hunting) konseptini proaktif güvenlik operasyonlarının temeline yerleştirir. Analistlerin ham log verileri üzerinde anlık (ad-hoc) araştırmalar yapabilmesi, makine öğrenmesi (Spark MLlib) ile bilinmeyen tehditleri modelleyebilmesi ve dinamik formlar aracılığıyla parametrik avlanma arayüzleri oluşturabilmesi Zeppelin'in mimari esnekliğinden kaynaklanmaktadır.6  
Bu araştırma raporu, Apache Zeppelin'in çekirdek mimarisini, WebSocket ve Thrift protokolleri üzerinden gerçekleşen asenkron kod çalıştırma akışını, çoklu SOC ortamlarında hayati önem taşıyan yorumlayıcı (interpreter) izolasyon stratejilerini ve bu stratejilerin Java Sanal Makinesi (JVM) bellek tüketimine etkilerini en ince teknik ayrıntılarına kadar incelemektedir. Ayrıca, çoklu dil desteğinin sağladığı kesintisiz bağlam (context) paylaşımı ve geleneksel İş Zekası (BI) araçları ile olan farklılıklar, siber güvenlik analitiği senaryoları üzerinden kapsamlı bir biçimde sentezlenmektedir.

## **1\. Çekirdek Mimari ve Yorumlayıcı (Interpreter) İzolasyonu**

Apache Zeppelin'in 0.11.1 sürümündeki mimari zarafetinin temelinde, istemci arayüzü ile veri işleme motorlarını birbirinden soyutlayan modüler "Yorumlayıcı" (Interpreter) tasarımı yatmaktadır. Zeppelin, varsayılan olarak yirmiden fazla farklı dili ve veri kaynağını (Scala, Python, R, SQL, JDBC, Shell) destekler.4 Ancak bu dillerin Zeppelin'in ana sunucu sürecinde (daemon) çalıştırılması, bellek sızıntıları (memory leaks) veya hatalı kod yürütmeleri durumunda tüm sistemin çökmesine yol açabileceği için oldukça riskli bir mimari yaklaşımdır. Bu riski ortadan kaldırmak için Zeppelin, asenkron, olay güdümlü (event-driven) ve RPC (Remote Procedure Call) tabanlı izole bir iletişim mimarisi kullanır.9

## **1.1. WebSocket'ten Spark Yorumlayıcısına Kod Çalıştırma Akışı**

Siber güvenlik analisti, Zeppelin web arayüzünde (Frontend) örneğin %spark.pyspark sihirli kelimesi (magic word) ile başlayan bir kod bloğu yazıp çalıştır tuşuna bastığında, sistemin arka planında çok katmanlı bir veri iletim akışı tetiklenir. Bu sürecin adım adım mimari işleyişi aşağıda detaylandırılmıştır:

1. **Kullanıcı Etkileşimi ve WebSocket Mesajının Oluşturulması:** Tarayıcı (Browser) üzerindeki Angular/JavaScript tabanlı arayüz, kullanıcının "Çalıştır" eylemini yakalar. HTTP'nin durumsuz (stateless) ve yüksek gecikmeli yapısını aşmak için Zeppelin, istemci ile sunucu arasında sürekli açık, çift yönlü bir WebSocket bağlantısı kurar.11 Kod bloğu ve meta veriler, JSON formatında bir yük (payload) haline getirilir. Bu JSON mesajı, RUN\_PARAGRAPH operasyon kodunu (opcode), not defteri kimliğini (noteId), ilgili paragrafın benzersiz kimliğini (paragraphId) ve varsa form parametrelerini barındırır.11  
2. **NotebookServer Sınıfının Mesajı Karşılaması:** Zeppelin ana sunucusunda (Zeppelin Server), /ws uç noktasını (endpoint) dinleyen NotebookServer sınıfı bu JSON mesajını teslim alır.14 Mesajın yapısal bütünlüğü ve kullanıcının yetki kontrolleri (Authorization/Authentication) tamamlandıktan sonra, Note nesnesi üzerinden ilgili Paragraph nesnesi tanımlanır.14  
3. **Yorumlayıcının Çözümlenmesi (Interpreter Resolution):** InterpreterFactory, paragrafın metin içeriğinin en başındaki sihirli kelimeyi (örneğin %spark.pyspark) okur.15 Bu sihirli kelime, kodun hangi dil motoruna (ve ilgili "Interpreter Group"una) yönlendirileceğini belirler. Eğer sihirli kelime kullanılmamışsa, sistem yapılandırılan varsayılan yorumlayıcıyı (default interpreter) atar.10  
4. **İş Zamanlayıcısına (Scheduler) İletim:** Paragraf doğrudan yürütülmez. Zeppelin, karmaşık iş yüklerini yönetebilmek için her yorumlayıcıya özel bir Scheduler (Zamanlayıcı) tanımlar (örneğin FIFO veya Spark için Fair Scheduler).10 Paragraf, zamanlayıcının kuyruğuna bir Job olarak eklenir. Zamanlayıcı, kaynakların uygunluğuna göre paragrafın statüsünü "PENDING" (Beklemede) durumundan "RUNNING" (Çalışıyor) durumuna geçirir.10  
5. **Apache Thrift Üzerinden Uzak İşlem Çağrısı (RPC):** Yalıtımı ve güvenliği sağlamak için, seçilen Spark Yorumlayıcısı (SparkInterpreter), Zeppelin ana sürecinin dışında, işletim sistemi üzerinde tamamen bağımsız bir JVM süreci (RemoteInterpreterServer) olarak çalışır.9 Zeppelin Server ile bu bağımsız JVM süreci arasındaki veri transferi, serileştirme ve komut iletimi yüksek performanslı Apache Thrift protokolü kullanılarak TCP/IP soketleri üzerinden gerçekleştirilir.9  
6. **Kodun Yürütülmesi ve Py4J Köprüsü:** Thrift üzerinden uzak JVM'e (RemoteInterpreter) ulaşan kod parçası, eğer bir Python koduysa, doğrudan Scala/Java ortamında çalıştırılamaz. Bu noktada PySparkInterpreter sınıfı devreye girer ve kodu Py4J kütüphanesi aracılığıyla arka planda başlatılan izole bir Python işçi (worker) sürecine aktarır.19 Python süreci kodu işletir ve ortaya çıkan sonuçlar, görselleştirme verileri veya konsol çıktıları aynı iletişim hattı üzerinden (Python \-\> Py4J \-\> RemoteInterpreter JVM \-\> Thrift \-\> Zeppelin Server \-\> WebSocket) tersine bir akışla saliseler içerisinde analizcinin tarayıcı ekranına itilir (push).4

Bu asenkron mimari, devasa bir veri setinde saatlerce sürebilecek bir anomali tespiti modelinin (Machine Learning Job) arka planda çalışmasına izin verirken, analistin arayüzde diğer işlemleri yapmasına ve WebSocket üzerinden canlı ilerleme çubuğunu (progress bar) kesintisiz izlemesine imkan tanır.4

## **1.2. Çoklu SOC Analisti Ortamında İzolasyon Stratejileri ve JVM Analizi**

Modern bir Güvenlik Operasyon Merkezi'nde, aynı Zeppelin sunucusu üzerinde Seviye 1 (L1) Triage analistleri, Seviye 2 (L2) Olay Müdahale uzmanları ve Seviye 3 (L3) Tehdit Avcıları eşzamanlı olarak çalışır. Onlarca kullanıcının petabaytlarca veriyi sorguladığı bu ortamda, kaynakların tahsisi ve kullanıcıların birbirlerinin kod süreçlerini etkilememesi (izolasyon) kritik bir mimari problemdir.  
Apache Zeppelin (v0.11.1), bu çok kiracılı (multi-tenant) çalışma gereksinimlerini karşılayabilmek için yorumlayıcıları **'Shared' (Paylaşımlı)**, **'Scoped' (Kapsamlı)** ve **'Isolated' (İzole)** olmak üzere üç farklı modda başlatma esnekliği sunar.18 Bu modlar ayrıca "Not Defteri Başına" (Per Note) veya "Kullanıcı Başına" (Per User) şeklinde iki farklı boyutta (dimension) yapılandırılabilir.25  
Aşağıda, bu modların mimari düzeyde nasıl yapılandığı, JVM bellek tahsisindeki farklılıkları ve çoklu SOC operasyonlarına olan etkileri detaylı olarak analiz edilmiştir.

#### **1.2.1. Shared (Paylaşımlı) Mod ve Etkileri**

Shared mod, Zeppelin'in kaynak tüketimini en aza indirmek için tasarlanmış en temel izolasyon modelidir.26 Bu modda yapılandırılan bir yorumlayıcı grubuna (örneğin Spark grubuna) bağlı olan tüm kullanıcılar ve tüm not defterleri, tek bir işletim sistemi süreci (JVM) ve tek bir oturum (session) üzerinden sunulur.18

* **JVM ve Bellek Mimarisi:** Sunucu üzerinde sadece bir adet RemoteInterpreterServer JVM'i başlatılır. Bu JVM'in içerisinde sadece bir adet SparkContext ve tek bir Scala REPL / Python Shell ortamı oluşturulur.18 Eğer spark.driver.memory parametresi 4GB olarak belirlendiyse, tüm platformdaki tüm not defterleri bu 4GB'lık yığın (Heap) alanını ortaklaşa kullanmak zorundadır.16  
* **Analitik Kapsam ve Paylaşım:** Ortak bir oturum kullanıldığı için, Analist A'nın "Av\_Hipotezi\_1" isimli not defterinde tanımladığı zararli\_domainler \= \['apt-c2.com', 'evil.net'\] şeklindeki bir liste, Analist B'nin "Firewall\_Analizi" not defterinde aynı isimle doğrudan erişilebilir haldedir.18  
* **SOC Operasyonları İçin Riskler:** Bu mod, kalabalık bir siber güvenlik ekibi için son derece elverişsiz ve risklidir. İzolasyonun olmaması, veri güvenliği (bir analistin hassas veriye diğerlerinin erişimine açık şekilde müdahale etmesi) riskini doğurur. Daha önemlisi, eğer kıdemli bir analist çok büyük bir veri çerçevesini (DataFrame) yanlışlıkla ana belleğe çeken (örneğin collect() metodu ile) bir kod çalıştırırsa, bu durum doğrudan "Java.lang.OutOfMemoryError: Java heap space" hatasına yol açar.28 Bu çökme, paylaşılan tek JVM'i sonlandıracağı için o an Zeppelin üzerinde analiz yapan *tüm* SOC personelinin işlemlerinin aniden kesintiye uğramasına neden olur.18

#### **1.2.2. Scoped (Kapsamlı) Mod ve ClassLoader Mekanizması**

Scoped mod, sınırlı bellek kaynaklarına sahip sistemlerde izolasyon gereksinimlerini karşılamak amacıyla tasarlanmış melez (hibrit) bir mimaridir.18 Zeppelin, Scoped modda yine tüm not defterleri için sadece bir adet ortak Yorumlayıcı JVM süreci çalıştırır; ancak bu tek süreç içerisinde her not defterine (veya kullanıcıya) özel bağımsız oturumlar (sessions) yaratır.18

* **Java ClassLoader ile Mantıksal İzolasyon:** Yalnızca tek bir JVM (işletim sistemi süreci) olmasına rağmen Zeppelin, arka planda farklı Java ClassLoader örnekleri oluşturarak her not defterinin kod çalışma alanını mantıksal olarak birbirinden ayırır.10 Bu sayede, "Kapsamlı Not Defteri" (Scoped Per Note) modunda her not defteri kendi özel Scala REPL ortamına veya kendi Python sözlüğüne (dictionary) sahip olur.27  
* **Değişken İzolasyonu:** Analistlerin oluşturduğu değişkenler (örneğin Python'daki veri çerçevesi isimleri veya fonksiyonlar), birbirlerinin çalışma alanlarına sızmaz veya birbirlerinin üzerine yazmaz.18 Bu durum, analistlerin çakışma korkusu olmadan aynı isimlendirme standartlarını kullanabilmesini sağlar.  
* **SparkContext Paylaşımı ve Fair Scheduler (Adil Zamanlayıcı):** Kapsamlı (Scoped) modun en can alıcı noktası, oturumların ayrılmasına rağmen tüm not defterlerinin arka planda **tek bir SparkContext ve SparkSession** nesnesini ortaklaşa kullanmaya devam etmesidir.16 Bu, bellek optimizasyonu sağlar. Çok sayıda analistin aynı Spark kümesine eşzamanlı SQL veya PySpark sorgusu göndermesi durumunda bir darboğaz yaşanmaması için Zeppelin, zeppelin.spark.concurrentSQL parametresini devreye sokar ve Spark'ın "Fair Scheduler" (Adil Zamanlayıcı) mekanizmasını kullanır.16 Analistler, paragraflarına %spark(pool=tehdit\_avi\_havuzu) gibi parametreler atayarak, tek bir SparkContext üzerinde koşan işlemlerin havuzlar halinde adil bir şekilde donanım kaynaklarını paylaşmasını sağlayabilirler.16  
* **Dezavantajlar:** İzolasyon mantıksal (ClassLoader bazlı) olduğu için, paylaşılan ana JVM süreçlerinden biri kritik bir çökme (örneğin JVM kernel katmanında öldürülürse) yaşadığında, o JVM üzerinde barınan tüm not defteri oturumları yine de etkilenir.18

#### **1.2.3. Isolated (İzole) Mod ve İşletim Sistemi Seviyesinde Bağımsızlık**

Büyük ölçekli, üretim (production) seviyesindeki SOC ortamlarında, yüksek erişilebilirlik ve donanım stabilitesi için mutlak bir standart olarak kabul edilen moddur.18 "İzole Not Defteri" (Isolated Per Note) modunda, her yeni not defteri açıldığında (veya kullanıcı özelinde) işletim sistemi üzerinde tamamen yepyeni, ayrı bir Yorumlayıcı JVM süreci (Process) başlatılır.18

* **Mutlak Mimari Ayrım:** Her not defteri sadece kendine ait izole bir Scala/Python REPL ortamına sahip olmakla kalmaz, aynı zamanda tamamen kendine ait, sıfırdan oluşturulmuş bağımsız bir SparkContext ve SparkSession nesnesine sahip olur.16 Bu durum, her analistin kendi Spark Uygulaması (Spark Application) gibi davranması anlamına gelir.  
* **Hata İzolasyonu (Crash Tolerance):** Bir tehdit avcısı, hatalı bir Join işlemi (örneğin milyarlarca satırlık DNS logu ile Proxy loglarını yanlış bir anahtar üzerinde birleştirmeye çalışmak) sonucunda kendi Spark yorumlayıcısını ve JVM sürecini kilitlerse veya çökertirse, sistemdeki diğer hiçbir analist bu durumdan en ufak bir şekilde etkilenmez. Diğer süreçler, kendi bağımsız JVM'leri içerisinde çalışmaya devam eder.18  
* **Bellek (RAM) Tüketim Analizi:** Güvenliğin ve izolasyonun getirdiği büyük bir mimari maliyet vardır: Donanım tüketimi. Shared veya Scoped modda tek bir JVM spark.driver.memory kadar RAM tüketirken, Isolated modda bu tüketim lineer olarak katlanır.18 Örneğin, yorumlayıcı RAM limiti (ZEPPELIN\_INTP\_MEM veya spark.driver.memory) 2GB olarak yapılandırılmışsa ve sistemde eşzamanlı çalışan 20 farklı not defteri varsa, yalnızca Zeppelin sunucusu üzerinde (Spark Worker/Executor nodeları hariç) sırf yorumlayıcı sürücüleri (Driver) için anında 40GB bellek (RAM) tahsis edilmesi gerekir.16  
* **Dağıtık Mimaride Çözüm:** Bu yoğun bellek (RAM) tüketimi darboğazını aşmak ve ana Zeppelin sunucusunu (master node) korumak için, büyük veri mimarları Spark yorumlayıcılarını yarn-client veya yarn-cluster (tercihen cluster) modunda çalışacak şekilde yapılandırır.16 Böylece, her bir not defteri için oluşturulan ağır JVM süreçleri (Driver'lar), Zeppelin sunucusu üzerinde değil, Hadoop YARN kümesindeki farklı işçi (worker) düğümleri üzerinde dağıtık olarak ayağa kaldırılır.

Aşağıdaki tablo, bu üç temel modun siber güvenlik analitiği operasyonlarındaki mimari etkilerini özetlemektedir:

| İzolasyon Modu | JVM Süreç Mimarisi | SparkContext Durumu | Olası Hata/Çökme Etki Alanı | RAM (Bellek) Maliyeti | Değişken Paylaşım Mekanizması | SOC Kullanım Önerisi |
| :---- | :---- | :---- | :---- | :---- | :---- | :---- |
| **Shared** | Tek Sistem JVM'i | Herkes İçin Tek (Ortak) | Sistemdeki tüm analistlerin çalışması durur | En Düşük (Tek tahsisat) | Doğrudan (Riskli) | Bireysel denemeler, POC ortamları |
| **Scoped** | Tek JVM, Çoklu ClassLoader | Tek Context, Çoklu Havuz (Pool) | Tüm sistem etkilenir (JVM bazlı) | Düşük | ResourcePool üzerinden | Kısıtlı donanımlı küçük ekipler |
| **Isolated** | Her Not/Kullanıcı İçin Bağımsız JVM | Herkese Özel Ayrı Context | Sadece hata yapan analist etkilenir | En Yüksek (Lineer artış) | ResourcePool üzerinden | Profesyonel, büyük ölçekli SOC ortamları |

## **2\. Çoklu Dil Desteği ve Bellek İçi Bağlam (Context) Paylaşımı**

Gelişmiş Tehdit Avcılığı senaryolarında analistlerin karşılaştığı en büyük zorluklardan biri, veri temizleme, veri zenginleştirme (enrichment) ve analitik sorgulama aşamalarının farklı programlama yaklaşımları gerektirmesidir.6 Ham bir Syslog verisini Parse etmek, hatalı karakterleri ayıklamak ve düzenli ifadeler (Regex) ile çalışmak için Python (PySpark) oldukça pratik bir yapı sunarken; temizlenmiş bu veriler üzerinde grup işlemleri yapmak, pencere fonksiyonları (Windowing) kullanmak veya istatistiksel trendler aramak için SQL sözdizimi, güvenlik analistlerinin en hakim olduğu alandır.32  
Geleneksel mimarilerde bu iki farklı dili kullanmak, verinin bir disk birimine yazılıp (I/O operasyonu) oradan başka bir araçla geri okunmasını veya karmaşık ETL (Extract, Transform, Load) süreçlerini gerektirir.35 Ancak Apache Zeppelin'in "Poliglot" (çok dilli) yorumlayıcı yapısı, aynı not defteri (notebook) içerisinde ardışık paragraflarda farklı dilleri (%spark.pyspark, %spark.sql, %spark.r, %spark) birbiriyle tamamen entegre bir biçimde çalıştırmaya imkan tanır.4 Bu entegrasyonun gücü, diller arası geçişin disk üzerinden değil, doğrudan sunucu belleği (RAM) üzerinde, ortak bağlamlar (Contexts) üzerinden gerçekleşmesinden kaynaklanır.

## **2.1. SparkSession Üzerinden Kesintisiz DataFrame Sorgulaması**

Zeppelin mimarisinde, Spark Yorumlayıcı Grubu altındaki tüm alt yorumlayıcılar (Scala, Python, SQL, R) başlatıldıklarında, arka planda aynı merkezi SparkContext ve SparkSession (Spark 2.x ve üzeri için) JVM nesnelerini kullanacak şekilde kurgulanırlar (Shared veya Scoped modunda).31 Zeppelin, bu ana bileşenleri sc, spark ve sqlContext isimli nesne referansları olarak ilgili dillerin çalışma zamanlarına (runtime) otomatik olarak enjekte eder (inject).16  
Bu mimari tasarım, veri mühendisliği adımları ile güvenlik analitiği adımlarının aynı bellek alanında nasıl birleştirilebileceğine olanak sağlar.

#### **SOC Tehdit Avcılığı Senaryosu: Zararlı IP Temizleme ve SQL ile Sorgulama**

Bir tehdit avcısının, ağ üzerinde izinsiz veri sızdırma (Data Exfiltration) veya komuta-kontrol (C2) merkezleriyle haberleşen bir zararlıyı tespit etmek için proxy loglarını incelediğini varsayalım.38  
**Adım 1: PySpark ile Veri Temizleme (Data Cleansing)** Analist, not defterinin ilk paragrafında %spark.pyspark yorumlayıcısını kullanarak devasa ham metin dosyalarını okur, Python'ın zengin dize (string) manipülasyon yetenekleriyle eksik verileri siler, logları ayrıştırır ve içlerinden yalnızca belirli bir filtreye uyan IP adreslerini çekip yapılandırılmış bir "DataFrame" (Veri Çerçevesi) nesnesi oluşturur.40  
Bu veriyi SQL motorunda kullanılabilir hale getirmek için Python ortamında şu kodu çalıştırır: df\_temizlenmis\_loglar.createOrReplaceTempView("guvenlik\_loglari\_view").16  
*Mimari Derinlik:* Bu satır işletildiğinde veri asla diske veya veritabanına yazılmaz. PySpark, arka planda çalışan Java/Scala sanal makinesi ile iletişim kurarak Spark'ın iç optimizasyon motoru olan **Catalyst Optimizer**'ın geçici bellek içi kataloğuna (in-memory catalog) "guvenlik\_loglari\_view" adında mantıksal bir gösterici (pointer) kaydeder.16 Bu gösterici, bellek üzerindeki veri çerçevesinin dağıtık yapısını (RDD) işaret eder.43  
**Adım 2: Spark SQL ile Kesintisiz Analitik** Analist, hemen altındaki paragrafta hiçbir veri taşıma veya bağlama (connection string) işlemi yapmaksızın doğrudan SQL motoruna geçer (%spark.sql).31

SQL

%spark.sql  
SELECT kaynak\_ip, COUNT(\*) as baglanti\_sayisi, SUM(byte\_boyutu) as toplam\_transfer  
FROM guvenlik\_loglari\_view  
WHERE hedef\_port IN (53, 443\)  
GROUP BY kaynak\_ip  
ORDER BY toplam\_transfer DESC;

*Mimari Derinlik:* Spark SQL yorumlayıcısı, sorguyu aldığında doğrudan aynı, ortak SparkSession üzerinden işletir.16 Katalogda "guvenlik\_loglari\_view" isimli görünümü bulur, bunun PySpark tarafından önceden temizlenmiş ve zaten sunucu RAM'inde (veya işçi düğümlerin belleklerinde) hazır bekleyen veriye işaret ettiğini anlar.16 Veri üzerinden saniyeler içerisinde sorguyu çalıştırır ve sonucu Zeppelin arayüzüne (Frontend) tablo olarak gönderir.16 Bu kesintisiz bellek içi akış, bir Siber Tehdit Avcısının bir olay müdahalesi (Incident Response) sırasında ihtiyaç duyduğu reaksiyon hızını muazzam ölçüde artırır.45

## **2.2. ZeppelinContext (z) ve Py4J Köprüsü Üzerinden Nesne (Object) Değişimi**

Veri çerçevelerinin (DataFrames) TempView üzerinden paylaşılması Büyük Veri setleri için ideal olsa da, analistler çoğu zaman basit skaler değerleri (örneğin bir önceki hücrede makine öğrenmesi modeliyle hesaplanan bir anomali eşik değeri \- threshold), tarih formatlarını veya Python sözlüklerini (dictionaries) diller arası aktarmak isterler.47 Apache Zeppelin, bu gereksinimi karşılamak için tüm yorumlayıcı ortamlarına z isimli bir ZeppelinContext nesnesi enjekte eder.31

* **z.put() ve z.get() Mekanizması:** Scala ortamında (örneğin %spark yorumlayıcısında) hesaplanan bir "tehdit\_esik\_degeri" (threshold) z.put("hesaplanan\_esik", tehdit\_esik\_degeri) komutuyla ZeppelinContext'in dahili haritasına (Map) ve ResourcePool içerisine kaydedilir.18 Daha sonra alt satırdaki %spark.pyspark hücresinde, analist bu veriyi z.get("hesaplanan\_esik") yazarak çağırabilir.29  
* **Py4J ve Serileştirme:** Scala (JVM) ile Python gibi birbirinden tamamen farklı çalışma zamanı ortamları (runtimes) arasında nesne aktarımı yapmak teknik olarak zordur. Zeppelin, bu aktarımı başarmak için Py4J kütüphanesini kullanır.19 Python süreci, yerel bir ağ soketi üzerinden Zeppelin'in ana JVM'iyle iletişim kurar. z.get() komutu çağrıldığında, JVM tarafındaki Java nesnesi serileştirilerek (serialized) soket üzerinden Python'a gönderilir ve Python'da uygun bir tipe (örneğin Java String'den Python String'e, Java ArrayList'ten Python List'e) dönüştürülür (deserialized).20 Bu özellik, Scala tabanlı hızlı bir veri manipülasyonunun ardından, elde edilen kilit parametrelerin Python'ın meşhur scikit-learn, numpy veya matplotlib kütüphanelerine aktarılması için hayati bir veri yolu sağlar.4

## **3\. İnteraktif Tehdit Avcılığı ve Dinamik Formlar**

Tehdit avcılığı (Threat Hunting), siber güvenlik duvarlarının (Firewall), Antivirüs yazılımlarının veya kural tabanlı SIEM korelasyonlarının (statik uyarıların) gözden kaçırdığı, sistem içerisinde uzun süredir saklanan (Advanced Persistent Threats \- APT) veya normal sistem yöneticisi davranışlarını taklit ederek "toprakta yaşama" (Living off the Land \- LotL) taktikleri uygulayan saldırganları proaktif olarak arama pratiğidir.45 Klasik analitik araçlar, önceden yazılmış, parametreleri sabit (hardcoded) betikler sunar. Ancak Apache Zeppelin, sahip olduğu "Dinamik Formlar" (Dynamic Forms) mimarisi ile bu statik betikleri, etkileşimli, tekrarlanabilir ve her seviyeden analistin kullanabileceği analitik gösterge panellerine dönüştürür.4

## **3.1. Dinamik Formların (Dynamic Forms) Çekirdek Mimarisi**

Dinamik formlar, analistlerin yazdıkları arka plan kodlarının (örneğin SQL, Scala veya Python) içerisine, kullanıcı arayüzünden (Frontend) anlık veri girişi sağlayabilen metin kutuları, onay kutuları (checkbox) veya açılır listeler (dropdown/select) yerleştirmesine olanak tanıyan bir özellik setidir.7  
Zeppelin bu formları iki ana yöntemle işler 53:

1. **Şablonlama Dili (Template Language):** En yaygın kullanım şeklidir. SQL veya Shell gibi yorumlayıcılarda doğrudan metin içerisine gömülür. ${form\_degiskeni} şeklinde kullanılır. Örneğin ${Hedef\_Port=443, 22|80|443|3389} sözdizimi, arka planda bir metin okuyucusu tarafından (Parser) yakalanır ve arayüze varsayılan değeri "443" olan bir açılır liste çizer.52  
2. **Programatik Üretim (ZeppelinContext üzerinden):** PySpark veya Scala içerisinde, kod çalışma anında (runtime) z.input("isim") veya z.select("secim", \[("deger1", "Etiket1")\]) metotları kullanılarak arayüzde formlar oluşturulabilir.20

"Seçim değiştiğinde çalıştır" (Run on selection change) özelliği aktif edildiğinde, kullanıcı arayüzde bir form değerini değiştirdiği an, Zeppelin WebSocket üzerinden yeni değerleri içeren bir JSON mesajı (RUN\_PARAGRAPH) yollar ve ilgili hücreyi milisaniyeler içerisinde otomatik olarak tekrar tetikler (re-execute).52

## **3.2. Ağ Trafiği ve Güvenlik Duvarı Üzerinde Uygulamalı Senaryo**

Bir Olay Müdahale (Incident Response \- IR) yöneticisinin veya Kıdemli Tehdit Avcısının (Tier 3), kurumun petabaytlarca büyüklüğe ulaşmış ham güvenlik duvarı (Firewall), DNS ve EDR (Endpoint Detection and Response) logları üzerinde şüpheli iletişimleri tespit etmeye çalıştığını düşünelim.38 Saldırganların sızdırma (Exfiltration) işlemleri için yaygın olarak kullandığı SSH (22), DNS (53), HTTPS (443) ve RDP (3389) portlarına doğru gerçekleşen olağandışı veri hacimlerini (Byte aktarımlarını) arayacaktır.38  
Kıdemli analist, karmaşık tablo birleştirmeleri (JOIN) ve alt sorgular içeren bir Spark SQL yazabilir. Ancak bu araştırmanın, SQL yazmayı bilmeyen Seviye 1 (L1) SOC analistleri tarafından da günlük "rutin bir avlanma aracı" olarak kullanılabilmesini istemektedir. Bu amaçla Zeppelin Dinamik Formlarını kullanarak aşağıdaki kodu inşa eder:

SQL

%spark.sql  
SELECT   
    kaynak\_ip AS Source\_IP,   
    hedef\_ip AS Destination\_IP,   
    hedef\_port AS Target\_Port,   
    SUM(transfer\_edilen\_byte) as Toplam\_Veri\_Hacmi  
FROM guvenlik\_duvari\_loglari  
WHERE hedef\_port \= ${Kritik\_Port\_Secimi=443, 22(SSH)|53(DNS)|80(HTTP)|443(HTTPS)|3389(RDP)}  
  AND kaynak\_ip LIKE '%${Kaynak\_IP\_Ag\_Blogu=192.168.}%'  
  AND zaman\_damgasi \>= current\_timestamp() \- interval '${Kac\_Saat\_Geri\_Bakilacak=24} hours'  
GROUP BY kaynak\_ip, hedef\_ip, hedef\_port  
HAVING Toplam\_Veri\_Hacmi \> ${Minimum\_Byte\_Esik\_Degeri=5000000}  
ORDER BY Toplam\_Veri\_Hacmi DESC  
LIMIT 100;

**Senaryonun İşleyişi ve SOC Operasyonlarına Katkısı:** Bu kod yürütüldüğünde, Zeppelin motoru SQL metnini derlemeden hemen önce etiketleri (parametreleri) tanır ve paragrafın üst kısmına, analistin etkileşime girebileceği estetik dört adet kontrol elemanı çizer 4:

1. **Açılır Liste (Dropdown):** RDP, SSH, DNS gibi protokollerin kolayca seçilebileceği bir menü.53  
2. **Metin Kutusu:** Şüpheli olduğu düşünülen iç ağ IP bloğunun girileceği alan (örneğin sadece 10.10.x.x alt ağı).53  
3. **Zaman Parametresi:** Geçmişe dönük log tarama aralığı (örneğin son 48 saat).40  
4. **Eşik Değeri:** Sadece yüksek boyutlu sızıntıları yakalamak için eşik belirleyici.

Seviye 1 (L1) SOC analisti nöbeti devraldığında, hiçbir kodlama yapmadan veya arka plandaki Big Data mimarisini (YARN, Spark, HDFS) anlamak zorunda kalmadan sadece bu arayüzü kullanır.56 Açılır listeden "53(DNS)" portunu seçer ve eşik değerini artırır. Zeppelin arka planda anında SQL'i günceller, Spark kümesinde dağıtık işi çalıştırır ve "DNS Tunneling" (DNS tünelleme üzerinden veri hırsızlığı) potansiyeli taşıyan IP adreslerini saniyeler içinde ekrana bir çubuk grafik (Bar Chart) olarak basar.4  
Bu yöntem, siber güvenlikte "Tehdit Avcılığının Operasyonelleştirilmesi" olarak bilinir. Kompleks makine öğrenmesi veya veri mühendisliği teknikleri, herkesin kullanımına açık araçlara (Tooling) dönüştürülür.45

## **4\. İş Zekası (BI) Araçları ile Apache Zeppelin'in Karşılaştırması**

Siber güvenlik ekipleri devasa verileri görselleştirme ve analiz etme ihtiyacı duyduğunda, akla sıklıkla Tableau, Power BI veya Qlik gibi endüstri standardı İş Zekası (Business Intelligence \- BI) araçları gelir.6 Bu kurumsal BI araçları, önceden yapılandırılmış veritabanlarına (Data Warehouse) bağlanarak C-Level yöneticiler için "Ne oldu?" sorusunu yanıtlayan statik gösterge panelleri (dashboards), KPI (Key Performance Indicator) takipleri ve raporlamalar oluşturmada son derece başarılıdır.58  
Ancak söz konusu **Büyük Veri SIEM analitiği, anlık (ad-hoc) log keşfi, güvenlik araştırmaları ve makine öğrenmesi algoritmaları üzerinden bilinmeyen tehditleri (Unknown Threats) avlamak** olduğunda, Apache Zeppelin'in sunduğu programlanabilir (code-first) ve veri-işleme-odaklı mimari, geleneksel BI araçlarının sunduğu yeteneklerden kesin bir çizgiyle ayrışır.6

## **4.1. Ad-Hoc (Anlık/Doğaçlama) Tehdit Araştırmaları ve Veri Keşfi (Data Exploration) Esnekliği**

**Geleneksel BI Araçlarının Katılığı (Schema-on-Write Bağımlılığı):** Power BI veya Tableau gibi araçlar, verinin görselleştirilebilmesi için öncesinde temizlenmiş, anlamlı kolonlara ayrılmış, ilişkisel veri modelleri (Yıldız Şeması vb.) ile birbirine bağlanmış olmasını talep eder.6 Siber güvenlik dünyasında ise log verileri (örneğin Apache HTTP logları, karmaşık iç içe geçmiş AWS CloudTrail JSON logları, Windows Event Logları) çoğu zaman son derece dağınık, eksik, yapısız (unstructured) veya yarı yapısal (semi-structured) formatlardadır.3 Bir BI aracında bu veriyi inceleyebilmek için uzun soluklu bir ETL (Extract, Transform, Load) sürecinden geçmesi, şemaların önceden belirlenmesi ve veri ambarına yazılması gerekir.35 Bir tehdit avcısı yeni tespit edilen bir sıfır-gün (Zero-Day) zafiyetinin izlerini sürerken, veri mühendisliği ekibinin ETL boru hatlarını güncelleyip BI panolarına (dashboards) yansıtmasını günlerce bekleyemez.50  
**Apache Zeppelin'in Kod Merkezli (Code-Driven) Esnekliği (Schema-on-Read):** Zeppelin, gücünü kodlamadan alır. Bir analist, ağa yönelik yeni bir saldırı tekniği duyurulduğunda Zeppelin'i açarak doğrudan S3, HDFS veya Kafka üzerinde duran *ham* ve dokunulmamış log dosyalarına PySpark ile bağlanabilir.62 Loglar üzerinde saniyeler içinde "Okurken Şema Oluşturma" (Schema-on-Read) taktiğini uygular.40 Analist, Python kütüphanelerini kullanarak karmaşık "User-Agent" (Kullanıcı Aracısı) dizgilerini (strings) parçalamak (parsing), Regex yazarak komuta-kontrol komutlarını tespit etmek veya IP adreslerinden anında Geolocasyon (Coğrafi Konum) zenginleştirmesi yapmak gibi işlemleri tek bir hücrede halleder.40 Kodlamanın (data processing) ve görselleştirmenin (visualization) aynı arayüzde iç içe geçmiş olması 6, tehdit avcısına sınırsız bir veri keşfi (Data Exploration) ve doğaçlama reaksiyon özgürlüğü sunar.8

## **4.2. Makine Öğrenmesi (Spark MLlib) Kullanımı ve Anomali Tespiti Entegrasyonu**

Tehdit avcılığının en ileri boyutu, bilinen saldırı kurallarını (IOCs) veritabanında aramak değil; "Normal" olan sistem davranışını matematiksel olarak modelleyip, bu normalin çok dışına çıkan (Outlier / Anomali) bilinmeyen saldırı etkinliklerini istatistiksel makine öğrenmesi teknikleriyle tespit etmektir (UEBA \- User and Entity Behavior Analytics).45  
Geleneksel BI yazılımları, temel düzeyde trend analizi (forecasting) ve bazı otonom anketleme özelliklerine sahip olsalar da; veri üzerinde hiper-parametre (hyper-parameter) optimizasyonu yapmak, özel model eğitmek veya terabaytlarca veri üzerinde dağıtık algoritmalar koşturmak için tasarlanmamışlardır.8  
Apache Zeppelin ise arka planda doğrudan **Apache Spark'ın MLlib (Makine Öğrenmesi Kütüphanesi)** ile tam uyumlu çalışır.67  
**Makine Öğrenmesi (ML) Senaryosu:** Bir siber güvenlik analisti, EDR ve Firewall loglarını kullanarak kurum içi bilgisayarların internetle kurduğu bağlantı sayılarını, bağlantı sürelerini ve TCP hatalarını içeren bir "Özellik Matrisi" (Feature Vector) çıkarır.66 Ardından Zeppelin içerisindeki aynı not defterinde, veriyi dışarıya hiçbir araca aktarmadan şu adımları izler:

1. **Model Eğitimi:** Spark MLlib kullanarak bir K-Means Clustering (K-Ortalamalar Kümeleme) veya Gaussian Mixture Model (GMM) algoritmasını bu özellik matrisi ile eğitir.48  
2. **Anomali Etiketleme:** Milyonlarca ağ oturumu (session) analiz edilerek, "Merkezden" (Centroid) çok uzakta kalan, yani normal kullanıcıların internet gezinme alışkanlıklarına benzemeyen aşırı yüksek port taramaları veya periyodik sinyal (beaconing) hareketleri sergileyen cihazlar "Anomali (1)" olarak etiketlenir.48  
3. **Gerçek Zamanlı Görselleştirme:** Zeppelin'in matplotlib, seaborn veya dahili Angular arayüzleri sayesinde bu kümeleme analizi, 3 boyutlu bir saçılım grafiği (Scatter Plot) üzerinde anında görselleştirilir ve tehdit avcısı aykırı noktaları (Outliers) gözüyle anında tespit edebilir.4

Sonuç itibarıyla geleneksel İş Zekası (BI) araçları veriyi salt "Raporlamak" için var olurken; Apache Zeppelin esnek, kod-tabanlı ve dağıtık makine öğrenmesi destekli yapısıyla veriyi "Sorgulamak, İşlemek ve İçindeki Gizli Tehditleri Ortaya Çıkarmak" için biçilmiş kaftandır.6

## **Sonuç ve Stratejik Sentez**

Modern siber güvenlik mimarisinde devasa boyutlara ulaşan log ve olay verileri, klasik SIEM uygulamalarının depolama ve işleme kapasitelerini aşmaktadır. Bu darboğazı çözmek üzere kurgulanan Büyük Veri SIEM boru hatlarında Apache Zeppelin (v0.11.1), veri analitiği, veri manipülasyonu ve proaktif tehdit avcılığı (Threat Hunting) fonksiyonlarını tek bir çatı altında birleştiren stratejik bir platformdur.  
Zeppelin'in WebSocket ve Apache Thrift protokolleri üzerine inşa edilmiş asenkron yapısı, yoğun iş yüklerinin ana sunucuyu bloke etmeden, işletim sistemi üzerinde dağıtılmış ayrı JVM (Java Virtual Machine) süreçleri olarak yönetilmesine olanak tanır. Çok kullanıcılı (multi-tenant) SOC ortamlarında, 'Shared', 'Scoped' ve 'Isolated' yorumlayıcı modları, donanım kaynaklarının kullanımı (RAM) ile kullanıcı oturumlarının güvenliği ve çökme toleransı (crash tolerance) arasında hassas mimari kararlar alınmasını sağlar. Özellikle üretim (production) seviyesindeki büyük SOC birimlerinde tam yalıtım sağlayan 'Isolated' mod, stabilite açısından kritik bir öneme sahiptir.  
Poliglot yapısı sayesinde PySpark, Spark SQL ve Scala gibi dillerin aynı SparkSession ve ZeppelinContext (Py4J destekli) üzerinden veriyi bellekte kesintisiz paylaşabilmesi, analistlere veri temizleme ve siber sorgulama aşamaları arasında eşsiz bir akıcılık kazandırır. Bu kod-merkezli altyapı, Dinamik Formlar ile birleştiğinde; arka planda karmaşık algoritmalar (Spark MLlib ile anomali tespiti vb.) içeren araştırmalar, L1 ve L2 analistlerin kolayca tıklayıp kullanabileceği parametrik, paylaşılabilir ve tekrarlanabilir tehdit avcılığı panellerine dönüşür.  
Geleneksel İş Zekası (BI) araçlarının katı, şema-bağımlı yapılarına karşın, Apache Zeppelin'in esnek (Schema-on-Read) doğası, güvenlik ekiplerinin yapılandırılmamış devasa log yığınları içinde hızla doğaçlama (ad-hoc) keşifler yapmasına olanak tanır. Tüm bu mimari ve analitik yetenekler göz önüne alındığında Apache Zeppelin, yalnızca bir veri görselleştirme arayüzü değil; makine öğrenmesi, veri mühendisliği ve siber olay müdahale disiplinlerini tek noktada kesiştiren ve tehdit avcılığını operasyonelleştiren vazgeçilmez bir Büyük Veri Siber Güvenlik silahıdır.

#### **Alıntılanan çalışmalar**

1. SIEM Log Management: The Complete Guide \- Exabeam, erişim tarihi Mart 13, 2026, [https://www.exabeam.com/explainers/event-logging/events-and-logs/](https://www.exabeam.com/explainers/event-logging/events-and-logs/)  
2. Real Time Security Analytics in Data Lakehouses Using Apache Iceberg and Event Streaming \- YouTube, erişim tarihi Mart 13, 2026, [https://www.youtube.com/watch?v=5LC5aHElOM0](https://www.youtube.com/watch?v=5LC5aHElOM0)  
3. Real-Time Cloud Security Graphs with Apache Hudi and PuppyGraph, erişim tarihi Mart 13, 2026, [https://hudi.apache.org/blog/2025/10/02/Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/](https://hudi.apache.org/blog/2025/10/02/Real-Time-Cloud-Security-Graphs-Hudi+PuppyGraph/)  
4. Zeppelin \- Apache Software Foundation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/](https://zeppelin.apache.org/)  
5. Apache Zeppelin 0.11.1 Documentation:, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/](https://zeppelin.apache.org/docs/0.11.1/)  
6. Exploring Data Visualization Techniques in Apache Zeppelin \- Test-king.com, erişim tarihi Mart 13, 2026, [https://www.test-king.com/blog/exploring-data-visualization-techniques-in-apache-zeppelin/](https://www.test-king.com/blog/exploring-data-visualization-techniques-in-apache-zeppelin/)  
7. What is Dynamic Form? \- Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/latest/usage/dynamic\_form/intro.html](https://zeppelin.apache.org/docs/latest/usage/dynamic_form/intro.html)  
8. Ten Open-Source Business Intelligence Tools for Improved ROI and Productivity | by ODSC, erişim tarihi Mart 13, 2026, [https://odsc.medium.com/ten-open-source-business-intelligence-tools-for-improved-roi-and-productivity-f060f72cc00e](https://odsc.medium.com/ten-open-source-business-intelligence-tools-for-improved-roi-and-productivity-f060f72cc00e)  
9. Zeppelin distributed architecture design \- Google Docs, erişim tarihi Mart 13, 2026, [https://docs.google.com/document/d/1a8QLSyR3M5AhlG1GIYuDTj6bwazeuVDKCRRBm-Qa3Bw/edit](https://docs.google.com/document/d/1a8QLSyR3M5AhlG1GIYuDTj6bwazeuVDKCRRBm-Qa3Bw/edit)  
10. How Apache Zeppelin runs a paragraph | by Jongyoul Lee \- Medium, erişim tarihi Mart 13, 2026, [https://medium.com/apache-zeppelin-stories/how-apache-zeppelin-runs-a-paragraph-783a0a612ba9](https://medium.com/apache-zeppelin-stories/how-apache-zeppelin-runs-a-paragraph-783a0a612ba9)  
11. Apache Zeppelin Notebook REST API, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.7.0/rest-api/rest-notebook.html](https://zeppelin.apache.org/docs/0.7.0/rest-api/rest-notebook.html)  
12. How to ensure a WebSocket message is JSON string, preventing JSON.parse error?, erişim tarihi Mart 13, 2026, [https://stackoverflow.com/questions/45581266/how-to-ensure-a-websocket-message-is-json-string-preventing-json-parse-error](https://stackoverflow.com/questions/45581266/how-to-ensure-a-websocket-message-is-json-string-preventing-json-parse-error)  
13. Apache Zeppelin Notebook REST API, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/usage/rest\_api/notebook.html](https://zeppelin.apache.org/docs/0.11.1/usage/rest_api/notebook.html)  
14. NotebookServer.java \- apache/zeppelin \- GitHub, erişim tarihi Mart 13, 2026, [https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java](https://github.com/apache/zeppelin/blob/master/zeppelin-server/src/main/java/org/apache/zeppelin/socket/NotebookServer.java)  
15. Interpreter in Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/usage/interpreter/overview.html](https://zeppelin.apache.org/docs/0.11.1/usage/interpreter/overview.html)  
16. Spark Interpreter for Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.9.0/interpreter/spark.html](https://zeppelin.apache.org/docs/0.9.0/interpreter/spark.html)  
17. Writing a New Interpreter \- Apache Zeppelin 0.11.1 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/development/writing\_zeppelin\_interpreter.html](https://zeppelin.apache.org/docs/0.11.1/development/writing_zeppelin_interpreter.html)  
18. Interpreter Binding Mode \- Apache Zeppelin 0.11.1 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/usage/interpreter/interpreter\_binding\_mode.html](https://zeppelin.apache.org/docs/0.11.1/usage/interpreter/interpreter_binding_mode.html)  
19. Apache Zeppelin: Run paragraph from another using z.run() throws a null pointer exception, erişim tarihi Mart 13, 2026, [https://stackoverflow.com/questions/68558491/apache-zeppelin-run-paragraph-from-another-using-z-run-throws-a-null-pointer](https://stackoverflow.com/questions/68558491/apache-zeppelin-run-paragraph-from-another-using-z-run-throws-a-null-pointer)  
20. Python Interpreter \- Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.6.0/interpreter/python.html](https://zeppelin.apache.org/docs/0.6.0/interpreter/python.html)  
21. Solved: Can't get Pyspark interpreter to work on Zeppelin \- Cloudera Community \- 138002, erişim tarihi Mart 13, 2026, [https://community.cloudera.com/t5/Support-Questions/Can-t-get-Pyspark-interpreter-to-work-on-Zeppelin/td-p/138002](https://community.cloudera.com/t5/Support-Questions/Can-t-get-Pyspark-interpreter-to-work-on-Zeppelin/td-p/138002)  
22. Zeppelin thrift error “Can't get status information “ \- markobigdata, erişim tarihi Mart 13, 2026, [https://markobigdata.com/2016/03/18/zeppelin-thrift-error-cant-get-status-information/](https://markobigdata.com/2016/03/18/zeppelin-thrift-error-cant-get-status-information/)  
23. Spark with Zeppelin \- Apache Zeppelin 0.8.2 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.8.2/quickstart/spark\_with\_zeppelin.html](https://zeppelin.apache.org/docs/0.8.2/quickstart/spark_with_zeppelin.html)  
24. Interpreter Binding Mode \- Apache Zeppelin 0.8.2 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.8.2/usage/interpreter/interpreter\_binding\_mode.html](https://zeppelin.apache.org/docs/0.8.2/usage/interpreter/interpreter_binding_mode.html)  
25. Interpreter in Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/latest/usage/interpreter/overview.html](https://zeppelin.apache.org/docs/latest/usage/interpreter/overview.html)  
26. Key factors that affects Zeppelin's Performance \- Cloudera Community \- 248765, erişim tarihi Mart 13, 2026, [https://community.cloudera.com/t5/Community-Articles/Key-factors-that-affects-Zeppelin-s-Performance/ta-p/248765](https://community.cloudera.com/t5/Community-Articles/Key-factors-that-affects-Zeppelin-s-Performance/ta-p/248765)  
27. Interpreter Binding Mode \- Apache Zeppelin 0.8.0 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.8.0/usage/interpreter/interpreter\_binding\_mode.html](https://zeppelin.apache.org/docs/0.8.0/usage/interpreter/interpreter_binding_mode.html)  
28. Zeppelin: Scala Dataframe to python \- apache spark \- Stack Overflow, erişim tarihi Mart 13, 2026, [https://stackoverflow.com/questions/35719142/zeppelin-scala-dataframe-to-python](https://stackoverflow.com/questions/35719142/zeppelin-scala-dataframe-to-python)  
29. Apache Zeppelin Object Exchange for passing a DataFrame of feature vectors from the Scala Spark interpreter to PySpark to get a numpy array \- GitHub Gist, erişim tarihi Mart 13, 2026, [https://gist.github.com/jaredwinick/cabf91b2d8931d1db66fe9892aeeeb43](https://gist.github.com/jaredwinick/cabf91b2d8931d1db66fe9892aeeeb43)  
30. Apache Zeppelin, Interpreter mode explained | by Moon \- Medium, erişim tarihi Mart 13, 2026, [https://medium.com/@leemoonsoo/apache-zeppelin-interpreter-mode-explained-bae0525d0555](https://medium.com/@leemoonsoo/apache-zeppelin-interpreter-mode-explained-bae0525d0555)  
31. Spark Interpreter for Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/latest/interpreter/spark.html](https://zeppelin.apache.org/docs/latest/interpreter/spark.html)  
32. Apache Spark Interpreter ... \- Apache Zeppelin 0.11.1 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/interpreter/spark.html](https://zeppelin.apache.org/docs/0.11.1/interpreter/spark.html)  
33. Apache zeppelin binding mode \- Stack Overflow, erişim tarihi Mart 13, 2026, [https://stackoverflow.com/questions/45935630/apache-zeppelin-binding-mode](https://stackoverflow.com/questions/45935630/apache-zeppelin-binding-mode)  
34. Learn PySpark in Apache Zeppelin Notebook (Part-1) | by Jeff Zhang | Medium, erişim tarihi Mart 13, 2026, [https://zjffdu.medium.com/learn-pyspark-in-apache-zeppelin-notebook-part-1-3214abede98a](https://zjffdu.medium.com/learn-pyspark-in-apache-zeppelin-notebook-part-1-3214abede98a)  
35. Choosing the Best NoSQL Reporting Tool for Your Team \- Knowi, erişim tarihi Mart 13, 2026, [https://www.knowi.com/blog/choosing-the-best-nosql-reporting-tool-for-your-team/](https://www.knowi.com/blog/choosing-the-best-nosql-reporting-tool-for-your-team/)  
36. Spark Interpreter Group \- Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.5.0-incubating/interpreter/spark.html](https://zeppelin.apache.org/docs/0.5.0-incubating/interpreter/spark.html)  
37. Spark Interpreter for Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.8.0/interpreter/spark.html](https://zeppelin.apache.org/docs/0.8.0/interpreter/spark.html)  
38. Manage Cloud Logs for Effective Threat Hunting, erişim tarihi Mart 13, 2026, [https://media.defense.gov/2024/Mar/07/2003407864/-1/-1/0/CSI\_CloudTop10-Logs-for-Effective-Threat-Hunting.PDF](https://media.defense.gov/2024/Mar/07/2003407864/-1/-1/0/CSI_CloudTop10-Logs-for-Effective-Threat-Hunting.PDF)  
39. How can log analysis support advanced threat hunting efforts? \- Tencent Cloud, erişim tarihi Mart 13, 2026, [https://www.tencentcloud.com/techpedia/118670](https://www.tencentcloud.com/techpedia/118670)  
40. Cybersecurity with Python — Part4: Detecting Threats in Apache Logs | by Vaibhavi Tilak, erişim tarihi Mart 13, 2026, [https://medium.com/@vaibhavitilak17/cybersecurity-with-python-part4-detecting-threats-in-apache-logs-2090992e8f71](https://medium.com/@vaibhavitilak17/cybersecurity-with-python-part4-detecting-threats-in-apache-logs-2090992e8f71)  
41. Threat Hunting: An Advanced Guide to Log Analysis for Cybersecurity \- Trunc, erişim tarihi Mart 13, 2026, [https://trunc.org/learning/threat-hunting-using-your-logs-part-II](https://trunc.org/learning/threat-hunting-using-your-logs-part-II)  
42. Investigating Apache Access Logs with Splunk: A SOC Analyst's Guide \- Medium, erişim tarihi Mart 13, 2026, [https://medium.com/@sahankommunuri53/investigating-apache-access-logs-with-splunk-a-soc-analysts-guide-447e8a8ab387](https://medium.com/@sahankommunuri53/investigating-apache-access-logs-with-splunk-a-soc-analysts-guide-447e8a8ab387)  
43. Python (Spark) • PySpark reference • Overview \- Palantir, erişim tarihi Mart 13, 2026, [https://palantir.com/docs/foundry/transforms-python-spark/pyspark-overview/](https://palantir.com/docs/foundry/transforms-python-spark/pyspark-overview/)  
44. Interpreters in Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.7.0/manual/interpreters.html](https://zeppelin.apache.org/docs/0.7.0/manual/interpreters.html)  
45. Use Case: An example of threat hunting with Converged SIEM \- Logpoint, erişim tarihi Mart 13, 2026, [https://logpoint.com/en/blog/threat-hunting-with-converged-siem](https://logpoint.com/en/blog/threat-hunting-with-converged-siem)  
46. Intro to Log Analysis | SOC Level 2- Log Analysis | TryHackMe Walkthrough \- IritT \- Medium, erişim tarihi Mart 13, 2026, [https://iritt.medium.com/intro-to-log-analysis-soc-level-2-log-analysis-tryhackme-walkthrough-50e8004337de](https://iritt.medium.com/intro-to-log-analysis-soc-level-2-log-analysis-tryhackme-walkthrough-50e8004337de)  
47. Zeppelin-Context \- Apache Zeppelin 0.9.0 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.9.0/usage/other\_features/zeppelin\_context.html](https://zeppelin.apache.org/docs/0.9.0/usage/other_features/zeppelin_context.html)  
48. Detecting Anomalies in Media Streams With Apache Spark \- Hydrolix, erişim tarihi Mart 13, 2026, [https://hydrolix.io/blog/detecting-media-anomalies/](https://hydrolix.io/blog/detecting-media-anomalies/)  
49. Zeppelin-Context \- Apache Zeppelin 0.8.1 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.8.1/usage/other\_features/zeppelin\_context.html](https://zeppelin.apache.org/docs/0.8.1/usage/other_features/zeppelin_context.html)  
50. 4 Types of Threat Hunting Tools & Top 8 Tools to Know in 2025 | CyCognito, erişim tarihi Mart 13, 2026, [https://www.cycognito.com/learn/threat-hunting/threat-hunting-tools/](https://www.cycognito.com/learn/threat-hunting/threat-hunting-tools/)  
51. How to Plan a Threat Hunt: Using Log Analytics to Manage Data in Depth \- Dataversity, erişim tarihi Mart 13, 2026, [https://www.dataversity.net/articles/how-to-plan-a-threat-hunt-using-log-analytics-to-manage-data-in-depth/](https://www.dataversity.net/articles/how-to-plan-a-threat-hunt-using-log-analytics-to-manage-data-in-depth/)  
52. Dynamic Form in Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.8.0/usage/dynamic\_form/intro.html](https://zeppelin.apache.org/docs/0.8.0/usage/dynamic_form/intro.html)  
53. Dynamic Form in Apache Zeppelin, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.7.0/manual/dynamicform.html](https://zeppelin.apache.org/docs/0.7.0/manual/dynamicform.html)  
54. Part 7\. Firewall Log Collection Made Easy | by SOCFortress \- Medium, erişim tarihi Mart 13, 2026, [https://socfortress.medium.com/part-7-firewall-log-collection-made-easy-3cee987d60b6](https://socfortress.medium.com/part-7-firewall-log-collection-made-easy-3cee987d60b6)  
55. Having trouble thinking of examples for firewall threat logging. : r/networking \- Reddit, erişim tarihi Mart 13, 2026, [https://www.reddit.com/r/networking/comments/1l4o1bn/having\_trouble\_thinking\_of\_examples\_for\_firewall/](https://www.reddit.com/r/networking/comments/1l4o1bn/having_trouble_thinking_of_examples_for_firewall/)  
56. Easy Log Analysis for Contract Threat Hunting? : r/AskNetsec \- Reddit, erişim tarihi Mart 13, 2026, [https://www.reddit.com/r/AskNetsec/comments/13qpfs7/easy\_log\_analysis\_for\_contract\_threat\_hunting/](https://www.reddit.com/r/AskNetsec/comments/13qpfs7/easy_log_analysis_for_contract_threat_hunting/)  
57. Threat Hunt Like a Pro in Splunk | Create Dynamic Dashboards to Hunt Host-Based Threats, erişim tarihi Mart 13, 2026, [https://www.youtube.com/watch?v=oIToSaf-Do8](https://www.youtube.com/watch?v=oIToSaf-Do8)  
58. Top Data Analysis Tools of 2025: An In-Depth Review \- SheetFlash, erişim tarihi Mart 13, 2026, [https://sheetflash.com/blog/top-data-analysis-tools-of-2024-an-in-depth-review](https://sheetflash.com/blog/top-data-analysis-tools-of-2024-an-in-depth-review)  
59. Business Intelligence Software: 10 Best Options Compared for 2026 \- Tinybird, erişim tarihi Mart 13, 2026, [https://www.tinybird.co/blog/business-intelligence-software](https://www.tinybird.co/blog/business-intelligence-software)  
60. Apache Zeppelin vs. Jupyter Notebook vs. Microsoft Power BI Comparison \- SourceForge, erişim tarihi Mart 13, 2026, [https://sourceforge.net/software/compare/Apache-Zeppelin-vs-Jupyter-Notebook-vs-Power-BI/](https://sourceforge.net/software/compare/Apache-Zeppelin-vs-Jupyter-Notebook-vs-Power-BI/)  
61. The Open Source Edge: Comparing top BI tools with their paid rivals \- Astrafy, erişim tarihi Mart 13, 2026, [https://astrafy.io/the-hub/blog/technical/the-open-source-edge-comparing-top-bi-tools-with-their-paid-rivals](https://astrafy.io/the-hub/blog/technical/the-open-source-edge-comparing-top-bi-tools-with-their-paid-rivals)  
62. Choosing the Best Software for Data Analysis \- Quadratic, erişim tarihi Mart 13, 2026, [https://www.quadratichq.com/blog/choosing-the-best-software-for-data-analysis](https://www.quadratichq.com/blog/choosing-the-best-software-for-data-analysis)  
63. Spark with Zeppelin \- Apache Zeppelin 0.11.1 Documentation, erişim tarihi Mart 13, 2026, [https://zeppelin.apache.org/docs/0.11.1/quickstart/spark\_with\_zeppelin.html](https://zeppelin.apache.org/docs/0.11.1/quickstart/spark_with_zeppelin.html)  
64. spark-streaming-memory.py \- GitHub, erişim tarihi Mart 13, 2026, [https://github.com/adaltas/spark-streaming-pyspark/blob/master/spark-streaming-memory.py](https://github.com/adaltas/spark-streaming-pyspark/blob/master/spark-streaming-memory.py)  
65. Apache Zeppelin: A Powerful Tool for Interactive Data Visualization \- Medium, erişim tarihi Mart 13, 2026, [https://medium.com/@shivanipanchal0204/apache-zeppelin-a-powerful-tool-for-interactive-data-visualization-362ed0a6629d](https://medium.com/@shivanipanchal0204/apache-zeppelin-a-powerful-tool-for-interactive-data-visualization-362ed0a6629d)  
66. Anomaly detection using Spark Structured Streaming and Spark ML on Databricks Lakehouse Platform | by Jakub Wszolek, PhD | Data Engineering and Analytics | Medium, erişim tarihi Mart 13, 2026, [https://medium.com/data-engineering-and-analytics/anomaly-detection-using-spark-structured-streaming-and-spark-ml-on-databricks-lakehouse-platform-5fc5f0ef5af0](https://medium.com/data-engineering-and-analytics/anomaly-detection-using-spark-structured-streaming-and-spark-ml-on-databricks-lakehouse-platform-5fc5f0ef5af0)  
67. Apache Spark and MLlib-Based Intrusion Detection System or How the Big Data Technologies Can Secure the Data \- ResearchGate, erişim tarihi Mart 13, 2026, [https://www.researchgate.net/publication/358123634\_Apache\_Spark\_and\_MLlib-Based\_Intrusion\_Detection\_System\_or\_How\_the\_Big\_Data\_Technologies\_Can\_Secure\_the\_Data](https://www.researchgate.net/publication/358123634_Apache_Spark_and_MLlib-Based_Intrusion_Detection_System_or_How_the_Big_Data_Technologies_Can_Secure_the_Data)  
68. Apache Spark and MLlib-Based Intrusion Detection System or How the Big Data Technologies Can Secure the Data \- MDPI, erişim tarihi Mart 13, 2026, [https://www.mdpi.com/2078-2489/13/2/58](https://www.mdpi.com/2078-2489/13/2/58)  
69. 10 Powerful Apache Spark Use Cases Across Industries \- upGrad, erişim tarihi Mart 13, 2026, [https://www.upgrad.com/blog/apache-spark-applications-use-cases/](https://www.upgrad.com/blog/apache-spark-applications-use-cases/)  
70. Anomaly Detection model uses Spark for training and Spark Streaming for testing \- GitHub, erişim tarihi Mart 13, 2026, [https://github.com/keiraqz/anomaly-detection](https://github.com/keiraqz/anomaly-detection)