spark.master                              spark://spark-master:7077
spark.sql.catalogImplementation           hive
spark.sql.warehouse.dir                   hdfs://namenode:8020/user/hive/warehouse
spark.hadoop.fs.defaultFS                 hdfs://namenode:8020
spark.hadoop.hive.metastore.uris          thrift://hive-metastore:9083
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version 2
spark.sql.sources.partitionOverwriteMode  dynamic
spark.streaming.stopGracefullyOnShutdown  true
spark.kafka.bootstrap.servers             kafka-broker:9092
spark.serializer                          org.apache.spark.serializer.KryoSerializer
